[package]
name = "markdown-preview"
version = "0.1.0"
authors = ["app"]

[dependencies]
base64 = "0.7"
comrak = "0.2"
html5ever = "0.20.0"
kuchiki = "0.6"
mime_guess = "1.8.2"
structopt = "0.1.0"
structopt-derive = "0.1.0"
tiny_http = "0.5"

[profile.release]
lto = true
